name: clang-format

on:
  # push:
  #   branches:
  #     - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        extensions: 'h,c'
        exclude: './clang-format-ignore'
        clangFormatVersion: 17
        inplace: True
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actor
        author_name: Clang Robot
        message: '[clang-format] Formatting changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
